version: "3"

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/
    networks:
      - app-network

  backend:
    container_name: favdes_back
    restart: always
    build: ./FAVDES
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./FAVDES:/code
    environment:
      POSTGRES_HOST: 'postgres'
    command: python /code/manage.py runserver 0.0.0.0:8000
    networks:
      - app-network

  frontend:
    container_name: favdes_front
    restart: always
    build: ./FAVDES_FRONT
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - app-network

    command:
      "npm run start"

networks:
  app-network:
    driver: bridge