# Generated by Django 3.0 on 2019-12-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, related_name='posts', to='destination.Taxonomy'),
        ),
    ]
