# Generated by Django 2.2.9 on 2019-12-25 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0003_post_taxonomies'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
