# Generated by Django 2.2.9 on 2020-01-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_auto_20191225_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taxonomies',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voters',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
