# Generated by Django 2.2.9 on 2019-12-24 17:06

import apps.media.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='path',
            field=sorl.thumbnail.fields.ImageField(max_length=500, upload_to=apps.media.models.path_and_rename, validators=[apps.media.models.validate_file_size]),
        ),
    ]
