# Generated by Django 2.2.9 on 2019-12-25 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_auto_20191224_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_avatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to=settings.AUTH_USER_MODEL),
        ),
    ]
